name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd auto-deploy-elysia
            git pull origin main
            git status

            # Ensure Bun is installed and up to date
            curl -fsSL https://bun.sh/install | bash
            source ~/.bashrc
            bun upgrade

            # Install dependencies
            bun install

            # Install PM2 globally if not already installed
            npm list -g | grep pm2 || npm install -g pm2

            # Create PM2 symlink
            sudo ln -sf "$(which pm2)" "/usr/local/bin/pm2"

            # Build the application (if necessary)
            # bun run build

            # Reload and restart your application
            pm2 reload AutoDeployElysia || pm2 start --interpreter ~/.bun/bin/bun src/index.ts --name AutoDeployElysia
            pm2 save

            echo "Current directory: $(pwd)"
            echo "Bun version: $(bun --version)"
            echo "PM2 version: $(pm2 -v)"
            echo "Application files:"
            ls -la
            echo "PM2 processes:"
            pm2 list
            echo "PM2 logs for AutoDeployElysia:"
            pm2 logs AutoDeployElysia --lines 50
